hdick/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('loader.urls', namespace='loader')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

loader/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'showall', views.show_all, name='showall'),
    url(r'fail', views.show_all, name='fail'),
    url(r'contact', views.contact, name='contact'),
    url(r'drop_size', views.drop_size, name='drop_size'),
    url(r'drop_success', views.drop_success, name='drop_success'),
    url(r'', views.index, name='index')
]

loader/models.py
from django.db import models
from django.core.files.storage import default_storage
from django.core.validators import MaxValueValidator, MinValueValidator

from hdick.settings import UPLOAD_DIR
from .scripts import validate_file_extension


class Upload(models.Model):
    upload = models.FileField(verbose_name='Choose file', storage=default_storage, upload_to=UPLOAD_DIR,
                              validators=[validate_file_extension])
    date_added = models.DateTimeField(auto_now_add=True)
    output_name = models.CharField(default='', max_length=20)
    color = models.BooleanField(default=True)
    base_width = models.IntegerField(help_text="Value must be between 100-800.", default=500,
                                     validators=[MinValueValidator(10), MaxValueValidator(800)])
    speed = models.FloatField(help_text="No negative numbers. Stay positive", default=0.5,
                              validators=[MinValueValidator(0)])


class UploadStats(models.Model):
    date = models.DateTimeField(auto_now_add=True)
    name = models.CharField(default='', max_length=20)
    number_of_files = models.IntegerField(default=0)
    sourceurl = models.CharField(default='', max_length=200)
    width_size = models.IntegerField(default=500)
    frames = models.FloatField(default=0.5)


class SizeChange(models.Model):
    size_file = models.FileField(verbose_name='Choose file', storage=default_storage, upload_to=UPLOAD_DIR,
                                 validators=[validate_file_extension])
    size_name = models.CharField(verbose_name='New filename', default='', max_length=20)
    size_date_added = models.DateTimeField(auto_now_add=True)
    new_size = models.IntegerField(help_text="kb. Minimum value is 50kb ", default=500, validators=[MinValueValidator(50)])


class SizeChangeStats(models.Model):
    size_stat_date = models.DateTimeField(auto_now_add=True)
    size_stat_name = models.CharField(default='', max_length=20)
    old_stat_size = models.IntegerField(default=500)
    new_stat_size = models.IntegerField(default=500)
    output_file_path = models.CharField(default='', max_length=100)

loader/forms.py
from django import forms
from django.forms import ModelForm
from .models import Upload, SizeChange


class UploadForm(ModelForm):
    class Meta:
        model = Upload
        fields = '__all__'
        widgets = {"upload": forms.FileInput(attrs={'multiple': True})}


class SizeChangeForm(ModelForm):
    class Meta:
        model = SizeChange
        fields = '__all__'
        widgets = {"size_file": forms.FileInput()}

loader/views.py
import os

from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse

from .models import Upload, UploadStats, SizeChange, SizeChangeStats
from .forms import UploadForm, SizeChangeForm
from .scripts import resize, make_gif, add_gif_to_db, translate_color, cut_size
from hdick.settings import BASE_DIR, STATICFILES_DIRS


def index(request):
    if request.method == 'POST':
        form = UploadForm(request.POST, request.FILES)
        files = request.FILES.getlist('upload')
        name = request.POST.get('output_name')
        request.session['name'] = name
        basewidth = request.POST.get('base_width')
        color_raw = request.POST.get('color')
        colour = translate_color(color_raw)
        speed = request.POST.get('speed')
        source = name+'.gif'

        if form.is_valid():
            for file in files:
                Upload.objects.create(upload=file, output_name=name, base_width=basewidth,
                                      color=colour, speed=speed)
            uploads = Upload.objects.filter(output_name=name, base_width=basewidth, speed=speed)

            # process images size/color
            try:
                filenames = []
                for i in uploads:
                    resize(str(i.upload), int(basewidth), colour)
                    filenames.append(str(i.upload))
            except FileNotFoundError:
                return render(request, 'loader/fail.html')
            else:
                # creates gif out of processed images
                make_gif(filenames, source, float(speed))
                # makes file class out of gif
                django_file = add_gif_to_db(source)
                # adds gif file class to loader.db + info for stats.db
                Upload.objects.create(upload=django_file, output_name=name+'.gif')
                UploadStats.objects.create(name=name, number_of_files=len(filenames),
                                     sourceurl=source, width_size=basewidth,
                                     frames=speed)

                return HttpResponseRedirect(reverse('loader:showall'))
        else:
            form = UploadForm()
            return render(request, 'loader/index.html', {'form': form})

    else:
        form = UploadForm()
        return render(request, 'loader/index.html', {'form': form})


# if jpg-gif conversion is successful, this view returns gif image
def show_all(request):
    name = request.session.get('name')
    uploads = Upload.objects.filter(output_name=name)
    gif = Upload.objects.filter(output_name=name+'.gif')
    gif_address = os.path.join(BASE_DIR, STATICFILES_DIRS[0] + name + '.gif')
    try:
        context = {'gif': gif_address}
    except AttributeError:
        form = UploadForm()
        return render(request, 'loader/index.html', {'form': form})

    else:
        # cleans files/database entries that are no longer needed
        for i in uploads:
            os.remove(str(i.upload))
        uploads.delete()
        gif.delete()
    return render(request, 'loader/showall.html', context)


def drop_size(request):
    if request.method == 'POST':
        size_form = SizeChangeForm(request.POST, request.FILES)
        size_name = request.POST.get('size_name')
        new_size = int(request.POST.get('new_size'))

        if size_form.is_valid():
            size_form.save()
            filefilter = SizeChange.objects.filter(size_name=size_name, new_size=new_size)
            extension = str(filefilter[0].size_file)[-4:]
            file = os.path.join(BASE_DIR, str(filefilter[0].size_file))
            # file size before processing
            old_size = os.stat(file).st_size
            # desired file size
            new_size = new_size*1000

            # checks if desired file size is smaller than size before processing
            if old_size <= new_size:
                size_form = SizeChangeForm()
                text = 'ERROR: Your new size must be smaller, than old one.'
                context = {'size_form': size_form, 'text': text}
                return render(request, 'loader/drop_size.html', context)

            else:
                # limits image to new file size, and cleans unnecessary files/db entries
                new_stat_size, output_file = cut_size(file, old_size, new_size, size_name,
                                                      extension)
                # adds info to  db stat table
                SizeChangeStats.objects.create(size_stat_name=size_name, old_stat_size=old_size,
                                                new_stat_size=new_stat_size,
                                               output_file_path=output_file)
                request.session['size_name'] = size_name
                request.session['extension'] = extension
                return HttpResponseRedirect(reverse('loader:drop_success'))

        else:
            size_form = SizeChangeForm()
            text = 'Choose JPG file and reduce its size.'
            context = {'size_form': size_form, 'text': text}
            return render(request, 'loader/drop_size.html', context)

    else:
        size_form = SizeChangeForm()
        text = 'Choose JPG file and reduce its size.'
        context = {'size_form': size_form, 'text': text}
        return render(request, 'loader/drop_size.html', context)


# if filesize change is successful this view returns link to new image
def drop_success(request):
    size_name = request.session.get('size_name')
    extension = request.session.get('extension')
    output_file = STATICFILES_DIRS[0] + size_name + extension
    return render(request, 'loader/drop_success.html', {'output': output_file})


# in case of critical error,view cleans all db "working table" entries and helps app to recover
def fail(request):
    Upload.objects.all().delete()
    return render(request, 'loader/fail.html')


def contact(request):
    return render(request, 'loader/contact.html')

loader/templates/loader/base.html
<!DOCTYPE html>
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>JPG2GIF converter</title>

    <!-- Bootstrap core CSS -->
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="../../assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="http://jpg2gif.vipserv.org/static/css/cover.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>

<div class="site-wrapper">

    <div class="site-wrapper-inner">

        <div class="cover-container">

            <div class="masthead clearfix">
                <div class="inner">
                    <h3 class="masthead-brand">JPG2GIF by drhans</h3>
                    <nav>
                        <ul class="nav masthead-nav">
                            <li class="active"><a href="{% url 'loader:index' %}">JPG2GIF</a></li>
                            <li><a href="{% url 'loader:drop_size' %}">Decrease image filesize</a></li>
                            <li><a href="{% url 'loader:contact' %}">Contact</a></li>
                        </ul>
                    </nav>
                </div>
            </div>

            <div class="inner cover">
                <h1 class="cover-heading">Convert jpg images to gif and more... </h1>

                {% block content %}{% endblock content %}
            </div>

            <div class="mastfoot">
                <div class="inner">
                    <p>Cover template for <a href="http://getbootstrap.com">Bootstrap</a>, by <a href="https://twitter.com/mdo">@mdo</a>.</p>
                </div>
            </div>

        </div>

    </div>

</div>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
<script src="../../dist/js/bootstrap.min.js"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
</body>
</html>

loader/templates/loader/contact.html
{% extends "loader/base.html" %}
{% block content %}

<div class="container">
    <p class="lead">Suggestions? Advises? Problems? Contact me at:</p>
    <div>
         <a href="mailto:contact@drhans.vipserver.org">contact@drhans.vipserver.org</a>
    </div>
</div> <!-- /container -->
{% endblock content %}

loader/templates/loader/drop_size.html
{% extends "loader/base.html" %}

{% block content %}
    <div class="container">
        <p class="lead">{{ text }}</p>

        <div>
            <form action="/loader:drop_size" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{  size_form.as_p }}
                <input type="submit" value="Upload" style="color:black" />
            </form>
        </div>
    </div>
{% endblock content %}

loader/templates/loader/drop_success.html
{% extends "loader/base.html" %}

{% block content %}
<div class="container">
    <h3>Your image filesize limited succefully! </h3>
    <div>
        <a href="{{ output }}">Click here to download.</a>
    </div>
</div>
{% endblock content %}

loader/templates/loader/fail.html
{% extends "loader/base.html" %}

{% block content %}
<p>Link expired or some kinda error. Self-repair initialized. Return to main menu and try again</p>
{% endblock content %}

loader/templates/loader/index.html
{% extends "loader/base.html" %}
{% block content %}
<div class="container">
    <p class="lead">Choose JPG files and convert them to GIF movie.
        <br> Images will be played in alphabetical order.</p>

    <div>
        <form action="/loader/" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{  form.as_p }}
            <p>Upload may take a while or two. Keep calm</p>
            <input type="submit" value="Upload" style="color:black" />
        </form>
    </div>
</div>
{% endblock content %}

loader/templates/loader/showall.html
{% extends "loader/base.html" %}

{% block content %}
<div class="container">
    <h3>To save file: mouse right click -> save image as</h3>
    <p class="lead">Preview:</p>
    <div>
        <img src = "{{ gif }}">
    </div>
</div>
{% endblock content %}